### PR TITLE
Bladerfv2 support

### LINKED ISSUE #17: Build fails against libbladerf 2.0
Hello folks,

I have an interest in using the Soapy python bindings with one of the new BladeRF Micro A4 boards. Unfortunately, I have run into problems trying to build SoapyBladeRF against versions of libbladerf that support the new board.

I have created 2 docker containers to help folks replicate my issue. They build the software in an Ubuntu 18.04 environment:
https://gist.github.com/sparklespdx/da169dc2614cf8d5f88751cabd9bc598

You can build and run the containers with something like this:
```
sudo docker build -f Dockerfile.bladeRF_git_2017.12-rc1 -t soapybladerf-build-test-case-1 . && \
sudo docker run -it --rm soapybladerf-build-test-case-1
```
The first container builds BladeRF release 2017.12-rc1 and Soapy, and then SoapyBladeRF. This is the version of BladeRF from the PPAs. This build works, but none of the software recognizes the A4 board. I made this test case mainly to validate that my build environment works.

The second container builds BladeRF and Soapy from the current master branch successfully. It tries to build SoapyBladeRF but the build fails. See the output below.

I am not sure if this is an easy or hard problem to solve; I am unfamiliar with the code base. I am going to at least make an attempt to figure out what's wrong and make a PR if I get somewhere. Any help or advice would be much appreciated.

Build failure output:

```
Step 18/20 : RUN cmake ../ && make && make install && ldconfig
 ---> Running in a260660b7386
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libbladeRF'
--   Found libbladeRF, version 2.0.0-git-074f7373-dirty
-- Found libbladeRF: /usr/local/include, /usr/local/lib/libbladeRF.so
-- LIBBLADERF_INCLUDE_DIRS - /usr/local/include
-- LIBBLADERF_LIBRARIES - /usr/local/lib/libbladeRF.so
-- Checking for bladerf_set_gain_mode API...
--   Reading /usr/local/include/libbladeRF.h...
--   libbladeRF supports the bladerf_set_gain_mode API
-- Performing Test HAS_STD_CXX11
-- Performing Test HAS_STD_CXX11 - Success
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Module bladeRFSupport configured with version: 0.3.5-4fa4566
-- Configuring done
-- Generating done
-- Build files have been written to: /work/SoapyBladeRF/build
Scanning dependencies of target bladeRFSupport
[ 20%] Building CXX object CMakeFiles/bladeRFSupport.dir/bladeRF_Registation.cpp.o
[ 40%] Building CXX object CMakeFiles/bladeRFSupport.dir/bladeRF_Settings.cpp.o
/work/SoapyBladeRF/bladeRF_Settings.cpp: In member function 'virtual double bladeRF_SoapySDR::getFrequency(int, size_t, const string&) const':
/work/SoapyBladeRF/bladeRF_Settings.cpp:411:69: error: cannot convert 'unsigned int*' to 'bladerf_frequency* {aka long unsigned int*}' for argument '3' to 'int bladerf_get_frequency(bladerf*, bladerf_channel, bladerf_frequency*)'
     int ret = bladerf_get_frequency(_dev, _dir2mod(direction), &freq);
                                                                     ^
In file included from /work/SoapyBladeRF/bladeRF_SoapySDR.hpp:26:0,
                 from /work/SoapyBladeRF/bladeRF_Settings.cpp:22:
/work/SoapyBladeRF/bladeRF_Settings.cpp: In member function 'virtual long long int bladeRF_SoapySDR::getHardwareTime(const string&) const':
/work/SoapyBladeRF/bladeRF_Settings.cpp:570:49: error: invalid conversion from 'bladerf_channel {aka int}' to 'bladerf_direction' [-fpermissive]
     const int ret = bladerf_get_timestamp(_dev, BLADERF_MODULE_RX, &ticksNow);
                                                 ^
/usr/local/include/libbladeRF.h:2345:15: note:   initializing argument 2 of 'int bladerf_get_timestamp(bladerf*, bladerf_direction, bladerf_timestamp*)'
 int CALL_CONV bladerf_get_timestamp(struct bladerf *dev,
               ^~~~~~~~~~~~~~~~~~~~~
/work/SoapyBladeRF/bladeRF_Settings.cpp: In member function 'virtual void bladeRF_SoapySDR::writeSetting(const string&, const string&)':
/work/SoapyBladeRF/bladeRF_Settings.cpp:823:50: error: 'bladerf_module' is not a class, namespace, or enumeration
                     bladerf_xb200_set_path(_dev, bladerf_module::BLADERF_MODULE_RX, bladerf_xb200_path::BLADERF_XB200_BYPASS);
                                                  ^~~~~~~~~~~~~~
In file included from /work/SoapyBladeRF/bladeRF_SoapySDR.hpp:26:0,
                 from /work/SoapyBladeRF/bladeRF_Settings.cpp:22:
/work/SoapyBladeRF/bladeRF_Settings.cpp:823:66: error: expected unqualified-id before '(' token
                     bladerf_xb200_set_path(_dev, bladerf_module::BLADERF_MODULE_RX, bladerf_xb200_path::BLADERF_XB200_BYPASS);
                                                                  ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:823:66: error: expected primary-expression before ')' token
                     bladerf_xb200_set_path(_dev, bladerf_module::BLADERF_MODULE_RX, bladerf_xb200_path::BLADERF_XB200_BYPASS);
                                                                  ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:889:58: error: 'bladerf_module' is not a class, namespace, or enumeration
             int ret = bladerf_xb200_set_filterbank(_dev, bladerf_module::BLADERF_MODULE_RX, filter);
                                                          ^~~~~~~~~~~~~~
In file included from /work/SoapyBladeRF/bladeRF_SoapySDR.hpp:26:0,
                 from /work/SoapyBladeRF/bladeRF_Settings.cpp:22:
/work/SoapyBladeRF/bladeRF_Settings.cpp:889:74: error: expected unqualified-id before '(' token
             int ret = bladerf_xb200_set_filterbank(_dev, bladerf_module::BLADERF_MODULE_RX, filter);
                                                                          ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:889:74: error: expected primary-expression before ')' token
             int ret = bladerf_xb200_set_filterbank(_dev, bladerf_module::BLADERF_MODULE_RX, filter);
                                                                          ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:898:42: error: 'bladerf_module' is not a class, namespace, or enumeration
             bladerf_xb200_get_path(_dev, bladerf_module::BLADERF_MODULE_RX, &_bladerf_xb200_path);
                                          ^~~~~~~~~~~~~~
In file included from /work/SoapyBladeRF/bladeRF_SoapySDR.hpp:26:0,
                 from /work/SoapyBladeRF/bladeRF_Settings.cpp:22:
/work/SoapyBladeRF/bladeRF_Settings.cpp:898:58: error: expected unqualified-id before '(' token
             bladerf_xb200_get_path(_dev, bladerf_module::BLADERF_MODULE_RX, &_bladerf_xb200_path);
                                                          ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:898:58: error: expected primary-expression before ')' token
             bladerf_xb200_get_path(_dev, bladerf_module::BLADERF_MODULE_RX, &_bladerf_xb200_path);
                                                          ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:903:46: error: 'bladerf_module' is not a class, namespace, or enumeration
                 bladerf_xb200_set_path(_dev, bladerf_module::BLADERF_MODULE_RX, bladerf_xb200_path::BLADERF_XB200_MIX);
                                              ^~~~~~~~~~~~~~
In file included from /work/SoapyBladeRF/bladeRF_SoapySDR.hpp:26:0,
                 from /work/SoapyBladeRF/bladeRF_Settings.cpp:22:
/work/SoapyBladeRF/bladeRF_Settings.cpp:903:62: error: expected unqualified-id before '(' token
                 bladerf_xb200_set_path(_dev, bladerf_module::BLADERF_MODULE_RX, bladerf_xb200_path::BLADERF_XB200_MIX);
                                                              ^
/work/SoapyBladeRF/bladeRF_Settings.cpp:903:62: error: expected primary-expression before ')' token
                 bladerf_xb200_set_path(_dev, bladerf_module::BLADERF_MODULE_RX, bladerf_xb200_path::BLADERF_XB200_MIX);
                                                              ^
make[2]: *** [CMakeFiles/bladeRFSupport.dir/bladeRF_Settings.cpp.o] Error 1
CMakeFiles/bladeRFSupport.dir/build.make:86: recipe for target 'CMakeFiles/bladeRFSupport.dir/bladeRF_Settings.cpp.o' failed
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bladeRFSupport.dir/all' failed
make[1]: *** [CMakeFiles/bladeRFSupport.dir/all] Error 2
make: *** [all] Error 2
Makefile:129: recipe for target 'all' failed
The command '/bin/sh -c cmake ../ && make && make install && ldconfig' returned a non-zero code: 2
```

### PR DESCRIPTION
**Pull request by guruofquality**
* resolves https://github.com/pothosware/SoapyBladeRF/issues/17

### CODE REVIEW

**Comment by sparklespdx** [comment]
I *think* the only things that still needs doing is MIMO and the gain modes, the driver now supports automatic gain control and the gain API was refactored. I am working on the gain API update.

These changes do pass the self test and you can send and receive samples.

**Comment by guruofquality** [comment]
> I think the only things that still needs doing is MIMO and the gain modes, the driver now supports automatic gain control and the gain API was refactored. I am working on the gain API update.

No problem, take your time. We can sort out the commits/pull requests when your ready. I can just force push over this branch any time and it will do a test build with the CI, which is cool/helpful too.

**Comment by sparklespdx** [comment]
ok cool! If you are OK with me pushing to this branch I can just put stuff here as I complete it, for now I pushed some gain stuff to https://github.com/pothosware/SoapyBladeRF/tree/bladerfv2-gain

**Comment by guruofquality** [comment]
> ok cool! If you are OK with me pushing to this branch I can just put stuff here

Sure no problem. go for it

**Comment by sparklespdx** [comment]
oof sorry about the confusion with github accounts. As it turns out, if you submit a commit with the sign-off email of another Github account, it looks like the other account made the commit! even though the @joshfarwell account doesn't have push rights to this repo! How interesting.

**Comment by guruofquality** [comment]
Feel free to rewrite the history however you see fit, its all good until its merged into the master. And if you want permissions for another account, let me know.

Anyway, the permissions are really just for the repo access itself. The commits pushed could be done by anybody. And I think github just parses the commits for the author email and associates that to a github account if it happens to exist, and you can associate multiple emails, though not sure if you can have the same email associated on multiple accounts.

**Comment by sparklespdx** [comment]
You're absolutely right, it looks like Github just takes the email and name in the sign off at their word and associates those commits with an account. I had my sign off with my work email by accident. Didn't know about that!

Anyway, I have a couple questions about the automatic gain API in Soapy. The bladeRF2 board supports multiple automatic rx gain modes, and does not support a manual mode:

https://github.com/Nuand/bladeRF/blob/master/host/libraries/libbladeRF/src/board/bladerf2/bladerf2.c#L434-L455

bladeRF1 supports the boolean values and `BLADERF_GAIN_DEFAULT` which is the same as the automatic mode:

https://github.com/Nuand/bladeRF/blob/master/host/libraries/libbladeRF/src/board/bladerf1/bladerf1.c#L176-L189

However, Soapy only knows about boolean values for automatic gain modes:

https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Device.hpp#L681

I have two questions:
- What's the way you generally like to handle this sort of thing? Do you usually make a custom method on Device or put it into writeSetting?
- What should we do when bladerf2 users call `Device::setGainMode()` and `getGainMode()`? Should we throw an error directing the user to the other API?

**Comment by guruofquality** [comment]
> bladeRF1 supports the boolean values and BLADERF_GAIN_DEFAULT which is the same as the automatic mode

I think BLADERF_GAIN_MGC is the manual gain control -- it just got renamed?
```
{
        FIELD_INIT(.name, "manual"),
        FIELD_INIT(.mode, BLADERF_GAIN_MGC)
},
```

so perhaps set gain mode should operate by switching between MGC and I guess just be one of the particular AGC options. However since there are more interesting gain modes, I think a writeSetting should also exist to enumerate those more detailed options.

**Comment by sparklespdx** [comment]
Oh! So it is! Cool, I will do that.

**Comment by rtucker** [comment]
Hi there!  Just checking to see if there's anything y'all need from our end to get this going... you're one of the first to port stuff over to libbladeRF 2, so don't hesitate to reach out :)  (I did chat w/ @sparklespdx a bit last week, but this offer is open to all y'all.)

Thanks :)

**Comment by guruofquality** [comment]
I think this branch is safe to merge and it gets things compiling. We can always add more fixes later. In any case, as far as merging. I was waiting on @sparklespdx to say when :-)

**Comment by sparklespdx** [comment]
@guruofquality @rtucker sorry, I got busy last week and haven't worked on this.

There are a couple functions in the gain API that still need to be updated and then I think this is ready to merge. I think I can finish that up today or tomorrow. MIMO support can be put in later.

**Comment by rtucker** [comment]
Cool, no worries.  I've had a couple people ask, so I figured I'd check in :)

For what it's worth, selecting between BLADERF_GAIN_DEFAULT and BLADERF_GAIN_MGC will likely be good enough for 99% of situations.  An application with a need for the other modes (fastattack/slowattack/hybrid) will also need to tweak a whole slew of parameters in the RFIC, and those aren't plumbed out to the library.

**Comment by sparklespdx** [comment]
@rtucker in that case I'll just implement the setGainMode and hasGainMode methods to toggle BLADERF_GAIN_MCG and BLADERF_GAIN_DEFAULT and worry about setting the special automatic gain modes at a later time.

**Comment by pk-mdt** [comment]
I was able to compile this branch and test on my micro hardware. I did notice that if a call is made to  specific v1 (bladerf original) commands, such as bladerf_set_sampling, it throws an error. I chased this down after trying to get the micro hardware to work in CubicSDR. it crashes with the error "bladerf_set_sampling(internal) returned -8 Operation not supported." The problem appears to be with     the code starting in line 913 of bladeRF_Settings.cpp (else if (key == "sampling_mode")). I was able to get Cubic up and running by changing the other options in the settings section of the code to "false" and bypassing the sampling mode section. I am hacking up the code in my fork with the changes I made to get it working.

**Comment by guruofquality** [comment]
@pk-r7 it looks like cubic sdr is calling writeSetting('sampling_mode', 'internal') to establish a default? or is this something you set. Anyway it could be a library issue with ```ret = bladerf_set_sampling(_dev, bladerf_sampling::BLADERF_SAMPLING_INTERNAL);``` Since this should not cause any side effects I think.

**Comment by pk-mdt** [comment]
@guruofquality yes when CubicSDR initializes it looks for SoapySDR modules, when it sees the bladerf is attached it iterates through the settings. Since the reset, eraseFPGA, and jump to bootloader settings have a single option, it does not give you an option to change it. The sampling mode should not even be an option for the V2 hardware as it is a V1 only option. My completely hacked up branch of this patch allows me to get the bladerf up and running, but to do it properly IMHO we should just skip over the sampling mode for V2 hardware and disable the other options (for v2) until they work on v2 hardware.

**Comment by pk-mdt** [comment]
Here is a copy of the interface.
cubic

**Comment by guruofquality** [comment]
@pk-r7 You have a v2 right? I added some checks to make sure these calls where only listed when it was a v1. Also loopack mode uses the new strings provided by bladerf_get_loopback_modes. Does this work on your setup? If everything is basically working for you, its probably safe to merge this.

**Comment by pk-mdt** [comment]
Yes I have a V2 . I also have a v1 that arrived today for a different project. I can test on that one as well. I tried with your latest changes and it now crashes with no useful error I can easily debug. I crashes when I select the device on the screen above, before it lists all of the options. It appears to be able to set the Sample rate on both inputs but then it crashes.

**Comment by rtucker** [comment]
I've been mulling over how to improve this on the libbladeRF side of things, and I don't think there's much else we can do if a function is not meaningful for a given device.

`bladerf_set_sampling` could simply return 0 and that would be okay (if misleading), but it is expected that `bladerf_get_sampling` (and the other getters) will pass back a value if returning 0, and having nothing to pass back is likely to have some weird side effects.

Suggestions are welcome... Nuand/bladeRF#602 is the issue we've got open for `bladerf_set_sampling`, although I think that's going to morph into a general "need a way to determine if a given API call is supported with a given device" thing.

I am keeping an eye on this thread, but as a reminder, https://github.com/Nuand/bladeRF/issues is the best place to report any libbladeRF misbehavior/bugs/implementation issues.  If it's not in there, it's not on my radar yet :)

**Comment by guruofquality** [comment]
Im going to merge this. Any segfaults I will need a backtrace. There is still an [open issue for the mimo packing](https://github.com/pothosware/SoapyBladeRF/issues/20). And eventually we can drop old driver support and get rid of all those ifdefs

**Pull request merged**
