### PR TITLE
enable channels in constructor, not stream

### LINKED ISSUE #30: setGain no working with bladeRF 2.0
Hi,

I'm not sure this is Soapy related or not. I have a program where I set the gain and then print it, to make sure it was set properly.

It works with a LimeSDR but with the bladeRF 2 the `SoapySDRDevice_setGain` works (ie it returns 0) but then the `SoapySDRDevice_getGain` always returns 60, no matter what I asked. I can even ask for a gain of -500 or +500, I won't get any error, while I would expect a `Provided parameter is out of range`, just like with `setFrequency` if I ask for 10GHz.

### PR DESCRIPTION
**Pull request by guruofquality**
this may affect certain settings to not have channels enabled at init time. This should fix some issues with setting the gain.

* resolves https://github.com/pothosware/SoapyBladeRF/issues/30

### CODE REVIEW

**Comment by KarlL2** [comment]
Actually this is not as simple as this. This commit fixes the issue with the RX gain (but maybe something should be fixed in libbladerf to handle that), but it breaks the transmission. I think the issue is with

https://github.com/Nuand/bladeRF/blob/896d2431b3a35a4b31b6e729386202ebf5fdc5c0/host/libraries/libbladeRF/doc/doxygen/sync_tx_meta.dox#L21

After calling `writeStream` several times, you get a timeout. It seems the buffers are all filled and nothing ever empty them.

**Comment by guruofquality** [comment]
> Remember to enable the front end via bladerf_enable_module() <i>after</i>
calling bladerf_sync_config(), and <i>before</i> attempting to call
bladerf_sync_tx().

Ok, so the change is incorrect  for transmit, but it might be OK for RX?

**Comment by guruofquality** [comment]
```
Remember to enable the front end via bladerf_enable_module() <i>after</i>
calling bladerf_sync_config(), and <i>before</i> attempting to call
bladerf_sync_rx().
```
Rx is the same. I think I will revert the commit. This is probably a libbladerf bug. I cant do anything about it in this wrapper.

**Comment by guruofquality** [comment]
I think the other option (if bladerf cant fix it in the driver) is to stash the gain when streaming and re-apply the gain once the enable() is called. I think a few of the rx only devices also do something like this.

**Comment by KarlL2** [comment]
The change seems indeed correct for RX but incorrect for TX.

I agree it would be best if this could be fixed in libbladerf instead. I opened https://github.com/Nuand/bladeRF/issues/746

**Comment by kristian1108** [comment]
Hi all -- does anyone know what the conclusion of this was? That issue (https://github.com/Nuand/bladeRF/issues/746) seems to have been deleted. If we're only using RX, seems like enabling the module is ok for now. Are there plans to fix this in other ways from Blade? Thanks!

**Pull request merged**
